### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cogumm** [aslamnd/speedy#1]
Hello, i'm reporting error:

$ speedy --help
/home/cogumm/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:762:in `report_activate_error': Could not find RubyGem speedy (>= 0) (Gem::LoadError)
    from /home/cogumm/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:219:in`activate'
    from /home/cogumm/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:1065:in `gem'
    from /home/cogumm/.rvm/gems/ruby-1.9.2-p0/bin/speedy:18:in`<main>'

**Comment by aslamnd** [comment]
Hello,

I'm working on the new version which will work on RVM and Linux + Mac platform. 

Thanks
